openapi: 3.0.1
info:
  description: App for softeng classes
  title: PayWay
  version: 1.0.0
servers:
- description: Local development server
  url: http://localhost:9115/api
paths:
  /tollStationPasses/{tollStationID}/{date_from}/{date_to}:
    get:
      description: Returns the total number of station passes from `date_from` to
        `date_to` for a given station.
      operationId: getTollStationPasses
      parameters:
      - description: ID of the toll station
        explode: false
        in: path
        name: tollStationID
        required: true
        schema:
          type: string
        style: simple
      - description: Start date in the format YYYYMMDD
        explode: false
        in: path
        name: date_from
        required: true
        schema:
          pattern: "^\\d{8}$"
          type: string
        style: simple
      - description: End date in the format YYYYMMDD
        explode: false
        in: path
        name: date_to
        required: true
        schema:
          pattern: "^\\d{8}$"
          type: string
        style: simple
      - description: Response format (json or csv). Defaults to json.
        explode: true
        in: query
        name: format
        required: false
        schema:
          default: json
          enum:
          - json
          - csv
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTollStationPasses_200_response'
          description: Success - Returns the toll passes data for the requested period
        "204":
          description: "No Content - The request was successful, but no data is available"
        "400":
          description: Bad Request - Invalid parameters or missing information
        "401":
          description: Unauthorized - Not used in the current API
        "500":
          description: Internal Server Error - An unexpected error occurred
        "415":
          description: "Unsupported Media Type - Format not supported (e.g., invalid\
            \ CSV format)"
      summary: Get total toll station passes from a period
      x-accepts:
      - application/json
components:
  schemas:
    Pass:
      properties:
        passIndex:
          type: integer
        passID:
          type: string
        timestamp:
          type: string
        tagID:
          type: string
        tagProvider:
          type: string
        passType:
          enum:
          - home
          - visitor
          type: string
        passCharge:
          type: string
      type: object
    getTollStationPasses_200_response_passList_inner:
      example:
        tagProvider: tagProvider
        passType: home
        passIndex: 6
        tagID: tagID
        passID: passID
        passCharge: passCharge
        timestamp: timestamp
      properties:
        passIndex:
          description: The pass number
          type: integer
        passID:
          description: ID of the pass
          type: string
        timestamp:
          description: Timestamp when the pass was recorded
          type: string
        tagID:
          description: Tag ID associated with the pass
          type: string
        tagProvider:
          description: The provider of the tag
          type: string
        passType:
          description: Type of pass
          enum:
          - home
          - visitor
          type: string
        passCharge:
          description: Charging details for the pass
          type: string
      type: object
    getTollStationPasses_200_response:
      example:
        periodTo: periodTo
        nPasses: 0
        requestTimestamp: requestTimestamp
        periodFrom: periodFrom
        passList:
        - tagProvider: tagProvider
          passType: home
          passIndex: 6
          tagID: tagID
          passID: passID
          passCharge: passCharge
          timestamp: timestamp
        - tagProvider: tagProvider
          passType: home
          passIndex: 6
          tagID: tagID
          passID: passID
          passCharge: passCharge
          timestamp: timestamp
        stationOperator: stationOperator
        stationID: stationID
      properties:
        stationID:
          description: ID of the station
          type: string
        stationOperator:
          description: Name of the worker at the station
          type: string
        requestTimestamp:
          description: Timestamp of the request
          type: string
        periodFrom:
          description: Start of the period (YYYYMMDD)
          type: string
        periodTo:
          description: End of the period (YYYYMMDD)
          type: string
        nPasses:
          description: Number of passes in the given period
          type: integer
        passList:
          items:
            $ref: '#/components/schemas/getTollStationPasses_200_response_passList_inner'
          type: array
      type: object
